export const DEFAULT_PRODUCT_EMOJI = '🍽️';

export const PRODUCT_ICON_CHOICES = [
  'fast-food',
  'restaurant',
  'pizza',
  'cafe',
  'ice-cream',
  'wine',
  'beer',
  'water',
  'basket',
  'pricetag',
  'nutrition',
  'egg',
  'fish',
  'leaf',
  'bonfire',
  'fast-food-outline',
  'restaurant-outline',
  'pizza-outline',
  'cafe-outline',
  'ice-cream-outline',
  'wine-outline',
  'beer-outline',
  'basket-outline',
  'pricetag-outline',
  'nutrition-outline',
  'egg-outline',
  'fish-outline',
  'leaf-outline',
] as const;